-- MySQL Script generated by MySQL Workbench
-- Sun Nov 22 20:59:33 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
-- SET MODE MYSQL; /*- this throws errors in the Workbench, so temporarily comment out when instantiating DB*/
-- SET IGNORECASE=TRUE; /*- this throws errors in the Workbench, so temporarily comment out when instantiating DB*/

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema staffdevelopment
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema staffdevelopment
-- -----------------------------------------------------

DROP TABLE IF EXISTS develomenttoolkit.`participation`;
DROP TABLE IF EXISTS develomenttoolkit.`reflection`;
DROP TABLE IF EXISTS develomenttoolkit.`objective`;
DROP TABLE IF EXISTS develomenttoolkit.`activity`;
DROP TABLE IF EXISTS develomenttoolkit.`siteUser`;
DROP TABLE IF EXISTS develomenttoolkit.`tag`;
DROP TABLE IF EXISTS develomenttoolkit.`role`;

CREATE SCHEMA IF NOT EXISTS develomenttoolkit;
USE develomenttoolkit ;

-- -----------------------------------------------------
-- Table `staffdevelopment`.`activity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS develomenttoolkit.`activity` (
    `activityID` INT NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(45) NOT NULL,
    `file` VARCHAR(45) NULL DEFAULT NULL,
    `description` VARCHAR(250) NULL DEFAULT NULL,
    PRIMARY KEY (`activityID`))
    ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `staffdevelopment`.`tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS develomenttoolkit.`tag` (
   `tagID` VARCHAR(11) NOT NULL,
   `description` VARCHAR(200) NULL DEFAULT NULL,
   `isOfficial` TINYINT(4) NULL DEFAULT NULL,
   PRIMARY KEY (`tagID`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `staffdevelopment`.`objective`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS develomenttoolkit.`objective` (
     `objectiveID` INT(11) NOT NULL,
     `Activity_activityID` INT(11) NOT NULL,
     `Tag_tagID` VARCHAR(11) NOT NULL,
     PRIMARY KEY (`objectiveID`),
     FOREIGN KEY (`Activity_activityID`)
         REFERENCES develomenttoolkit.`activity` (`activityID`)
         ON DELETE NO ACTION
         ON UPDATE NO ACTION,
     FOREIGN KEY (`Tag_tagID`)
         REFERENCES develomenttoolkit.`tag` (`tagID`)
         ON DELETE NO ACTION
         ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `staffdevelopment`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS develomenttoolkit.`role` (
    `role` VARCHAR(45) NOT NULL,
    `description` VARCHAR(45) NULL DEFAULT NULL,
    PRIMARY KEY (`role`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `staffdevelopment`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS develomenttoolkit.`siteUser` (
    `userID` INT(11) NOT NULL AUTO_INCREMENT,
    `emailAddress` VARCHAR(45) NOT NULL,
    `password` VARCHAR(100)NOT NULL,
    `userName` VARCHAR(20) NULL DEFAULT NULL,
    `active` BOOLEAN NULL DEFAULT NULL,
    `permissions` VARCHAR(30) NOT NULL,
    PRIMARY KEY (`userID`))
    ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `staffdevelopment`.`reflection`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS develomenttoolkit.`reflection` (
  `reflectionID` INT(11) NOT NULL AUTO_INCREMENT,
  `reflection` VARCHAR(45) NULL DEFAULT NULL,
  `Participation_participationID` INT(11) NOT NULL,
  `Tag_tagID` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`reflectionID`),
  FOREIGN KEY (`Tag_tagID`)
      REFERENCES develomenttoolkit.`tag` (`tagID`)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION)
    ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `staffdevelopment`.`participation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS develomenttoolkit.`participation` (
     `participationID` INT(11) NOT NULL AUTO_INCREMENT,
     `date` DATETIME NULL DEFAULT NULL,
     `siteUser_userID` INT(11) NOT NULL,
     `Activity_activityID` INT(11) NOT NULL,
     `Role_roleID` VARCHAR(45) NOT NULL,
     `Reflection_reflectionID` INT(45) NOT NULL,
     PRIMARY KEY (`participationID`),
     FOREIGN KEY (`Activity_activityID`)
         REFERENCES develomenttoolkit.`activity` (`activityID`)
         ON DELETE NO ACTION
         ON UPDATE NO ACTION,
     FOREIGN KEY (`siteUser_userID`)
         REFERENCES develomenttoolkit.`siteUser` (`userID`)
         ON DELETE NO ACTION
         ON UPDATE NO ACTION,
     FOREIGN KEY (`Role_roleID`)
         REFERENCES develomenttoolkit.`role` (`role`)
         ON DELETE NO ACTION
         ON UPDATE NO ACTION,
     FOREIGN KEY (`Reflection_reflectionID`)
         REFERENCES develomenttoolkit.`reflection` (`reflectionID`)
         ON DELETE NO ACTION
         ON UPDATE NO ACTION
)
    ENGINE = InnoDB;





-- -----------------------------------------------------
-- Dummy data for participation (temp)
-- -----------------------------------------------------